export type NotificationCategory =
  | 'attendance'
  | 'leave'
  | 'task'
  | 'ticket'
  | 'daily_report'
  | 'follow_up'
  | 'calendar'
  | 'employee'
  | 'system'
  | 'announcement'
  | 'security'

export type NotificationPriority = 'low' | 'normal' | 'high' | 'urgent'

export type NotificationChannel = 'in_app' | 'push' | 'email'

export interface NotificationEventDef {
  code: string
  module: string
  category: NotificationCategory
  priority: NotificationPriority
  channels: NotificationChannel[]
  titleTemplate: string
  messageTemplate: string
  actionUrl?: string
  quietHoursExempt: boolean
  sensitive: boolean
  idempotencyPrefix: string
}

export const NOTIFICATION_EVENTS: Record<string, NotificationEventDef> = {
  ATTENDANCE_PRE_CHECKOUT: {
    code: 'ATTENDANCE_PRE_CHECKOUT',
    module: 'attendance',
    category: 'attendance',
    priority: 'high',
    channels: ['in_app', 'push'],
    titleTemplate: 'Checkout Reminder',
    messageTemplate: 'Your required checkout time is approaching. Please prepare to check out.',
    actionUrl: '/attendance',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'att:pre_checkout',
  },
  ATTENDANCE_CHECKOUT_READY: {
    code: 'ATTENDANCE_CHECKOUT_READY',
    module: 'attendance',
    category: 'attendance',
    priority: 'high',
    channels: ['in_app', 'push'],
    titleTemplate: 'Checkout Ready',
    messageTemplate: 'You have completed the standard 9-hour attendance duration. You may now check out.',
    actionUrl: '/attendance',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'att:checkout_ready',
  },
  ATTENDANCE_CHECK_IN_CONFIRMED: {
    code: 'ATTENDANCE_CHECK_IN_CONFIRMED',
    module: 'attendance',
    category: 'attendance',
    priority: 'low',
    channels: ['in_app'],
    titleTemplate: 'Checked In',
    messageTemplate: 'Your check-in has been recorded successfully.',
    actionUrl: '/attendance',
    quietHoursExempt: true,
    sensitive: false,
    idempotencyPrefix: 'att:check_in_confirmed',
  },
  ATTENDANCE_CHECKOUT_CONFIRMED: {
    code: 'ATTENDANCE_CHECKOUT_CONFIRMED',
    module: 'attendance',
    category: 'attendance',
    priority: 'normal',
    channels: ['in_app'],
    titleTemplate: 'Checked Out',
    messageTemplate: 'Your checkout has been recorded. Attendance status has been calculated.',
    actionUrl: '/attendance',
    quietHoursExempt: true,
    sensitive: false,
    idempotencyPrefix: 'att:checkout_confirmed',
  },
  ATTENDANCE_HALF_DAY: {
    code: 'ATTENDANCE_HALF_DAY',
    module: 'attendance',
    category: 'attendance',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Half Day',
    messageTemplate: 'Your attendance has been marked as Half Day. Contact HR if you believe this is incorrect.',
    actionUrl: '/attendance',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'att:half_day',
  },
  ATTENDANCE_FULL_DAY: {
    code: 'ATTENDANCE_FULL_DAY',
    module: 'attendance',
    category: 'attendance',
    priority: 'low',
    channels: ['in_app'],
    titleTemplate: 'Full Day',
    messageTemplate: 'Your attendance has been marked as Full Day.',
    actionUrl: '/attendance',
    quietHoursExempt: true,
    sensitive: false,
    idempotencyPrefix: 'att:full_day',
  },
  ATTENDANCE_MISSING_CHECKOUT: {
    code: 'ATTENDANCE_MISSING_CHECKOUT',
    module: 'attendance',
    category: 'attendance',
    priority: 'high',
    channels: ['in_app', 'push'],
    titleTemplate: 'Missing Checkout',
    messageTemplate: 'You have not checked out today. Please check out or request a correction.',
    actionUrl: '/attendance',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'att:missing_checkout',
  },
  ATTENDANCE_CORRECTION_SUBMITTED: {
    code: 'ATTENDANCE_CORRECTION_SUBMITTED',
    module: 'attendance',
    category: 'attendance',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Correction Requested',
    messageTemplate: 'An attendance correction request has been submitted for review.',
    actionUrl: '/attendance/corrections',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'att:corr_submitted',
  },
  ATTENDANCE_CORRECTION_APPROVED: {
    code: 'ATTENDANCE_CORRECTION_APPROVED',
    module: 'attendance',
    category: 'attendance',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Correction Approved',
    messageTemplate: 'Your attendance correction request has been approved.',
    actionUrl: '/attendance',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'att:corr_approved',
  },
  ATTENDANCE_CORRECTION_REJECTED: {
    code: 'ATTENDANCE_CORRECTION_REJECTED',
    module: 'attendance',
    category: 'attendance',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Correction Rejected',
    messageTemplate: 'Your attendance correction request has been rejected. Please contact HR.',
    actionUrl: '/attendance/corrections',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'att:corr_rejected',
  },
  ATTENDANCE_CAMERA_LOCATION_ERROR: {
    code: 'ATTENDANCE_CAMERA_LOCATION_ERROR',
    module: 'attendance',
    category: 'attendance',
    priority: 'high',
    channels: ['in_app'],
    titleTemplate: 'Checkout Evidence Error',
    messageTemplate: 'Camera or location access failed during checkout. Please ensure permissions are granted.',
    actionUrl: '/attendance',
    quietHoursExempt: true,
    sensitive: false,
    idempotencyPrefix: 'att:evidence_error',
  },

  LEAVE_REQUEST_SUBMITTED: {
    code: 'LEAVE_REQUEST_SUBMITTED',
    module: 'leave',
    category: 'leave',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Leave Request Submitted',
    messageTemplate: 'A new leave request requires your review.',
    actionUrl: '/team-leave',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'leave:submitted',
  },
  LEAVE_PENDING_HR: {
    code: 'LEAVE_PENDING_HR',
    module: 'leave',
    category: 'leave',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Leave Pending HR Approval',
    messageTemplate: 'A leave request has been manager-approved and requires HR review.',
    actionUrl: '/leave-management',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'leave:pending_hr',
  },
  LEAVE_APPROVED: {
    code: 'LEAVE_APPROVED',
    module: 'leave',
    category: 'leave',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Leave Approved',
    messageTemplate: 'Your leave request has been approved.',
    actionUrl: '/my-leave',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'leave:approved',
  },
  LEAVE_REJECTED: {
    code: 'LEAVE_REJECTED',
    module: 'leave',
    category: 'leave',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Leave Rejected',
    messageTemplate: 'Your leave request has been rejected. Please check remarks for details.',
    actionUrl: '/my-leave',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'leave:rejected',
  },
  LEAVE_RETURNED: {
    code: 'LEAVE_RETURNED',
    module: 'leave',
    category: 'leave',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Leave Returned for Correction',
    messageTemplate: 'Your leave request has been returned for correction. Please review and resubmit.',
    actionUrl: '/my-leave',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'leave:returned',
  },
  LEAVE_CANCELLED: {
    code: 'LEAVE_CANCELLED',
    module: 'leave',
    category: 'leave',
    priority: 'normal',
    channels: ['in_app'],
    titleTemplate: 'Leave Cancelled',
    messageTemplate: 'Your leave request has been cancelled.',
    actionUrl: '/my-leave',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'leave:cancelled',
  },
  LEAVE_CANCELLATION_APPROVED: {
    code: 'LEAVE_CANCELLATION_APPROVED',
    module: 'leave',
    category: 'leave',
    priority: 'normal',
    channels: ['in_app'],
    titleTemplate: 'Leave Cancellation Approved',
    messageTemplate: 'Your leave cancellation request has been approved.',
    actionUrl: '/my-leave',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'leave:cancel_approved',
  },
  LEAVE_BALANCE_ADJUSTED: {
    code: 'LEAVE_BALANCE_ADJUSTED',
    module: 'leave',
    category: 'leave',
    priority: 'normal',
    channels: ['in_app'],
    titleTemplate: 'Leave Balance Adjusted',
    messageTemplate: 'Your leave balance has been adjusted by HR.',
    actionUrl: '/my-leave',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'leave:balance_adjusted',
  },
  LEAVE_MONTHLY_CREDIT: {
    code: 'LEAVE_MONTHLY_CREDIT',
    module: 'leave',
    category: 'leave',
    priority: 'low',
    channels: ['in_app'],
    titleTemplate: 'Monthly Leave Credit',
    messageTemplate: 'Your monthly leave balance has been credited.',
    actionUrl: '/my-leave',
    quietHoursExempt: true,
    sensitive: false,
    idempotencyPrefix: 'leave:monthly_credit',
  },
  LEAVE_UPCOMING: {
    code: 'LEAVE_UPCOMING',
    module: 'leave',
    category: 'leave',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Upcoming Approved Leave',
    messageTemplate: 'You have an approved leave starting soon.',
    actionUrl: '/my-leave',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'leave:upcoming',
  },

  TASK_ASSIGNED: {
    code: 'TASK_ASSIGNED',
    module: 'task',
    category: 'task',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Task Assigned',
    messageTemplate: 'A new task has been assigned to you. Please review and accept.',
    actionUrl: '/my-tasks',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'task:assigned',
  },
  TASK_ACCEPTED: {
    code: 'TASK_ACCEPTED',
    module: 'task',
    category: 'task',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Task Accepted',
    messageTemplate: 'Your task has been accepted by the assignee.',
    actionUrl: '/team-tasks',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'task:accepted',
  },
  TASK_REJECTED: {
    code: 'TASK_REJECTED',
    module: 'task',
    category: 'task',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Task Rejected',
    messageTemplate: 'A task has been rejected. Please review the rejection details.',
    actionUrl: '/team-tasks',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'task:rejected',
  },
  TASK_CHANGE_REQUEST: {
    code: 'TASK_CHANGE_REQUEST',
    module: 'task',
    category: 'task',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Task Change Request',
    messageTemplate: 'A change request has been submitted for a task. Please review.',
    actionUrl: '/task-review',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'task:change_request',
  },
  TASK_REQUEST_APPROVED: {
    code: 'TASK_REQUEST_APPROVED',
    module: 'task',
    category: 'task',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Task Request Approved',
    messageTemplate: 'Your task change request has been approved.',
    actionUrl: '/my-tasks',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'task:request_approved',
  },
  TASK_REQUEST_REJECTED: {
    code: 'TASK_REQUEST_REJECTED',
    module: 'task',
    category: 'task',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Task Request Rejected',
    messageTemplate: 'Your task change request has been rejected.',
    actionUrl: '/my-tasks',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'task:request_rejected',
  },
  TASK_REQUEST_RETURNED: {
    code: 'TASK_REQUEST_RETURNED',
    module: 'task',
    category: 'task',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Task Request Returned',
    messageTemplate: 'Your task change request has been returned for more information.',
    actionUrl: '/my-tasks',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'task:request_returned',
  },
  TASK_BLOCKER: {
    code: 'TASK_BLOCKER',
    module: 'task',
    category: 'task',
    priority: 'high',
    channels: ['in_app', 'push'],
    titleTemplate: 'Task Blocker Reported',
    messageTemplate: 'A blocker has been reported on a task. Please review.',
    actionUrl: '/team-tasks',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'task:blocker',
  },
  TASK_SUBMITTED: {
    code: 'TASK_SUBMITTED',
    module: 'task',
    category: 'task',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Task Submitted for Review',
    messageTemplate: 'A task has been submitted for your review.',
    actionUrl: '/task-review',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'task:submitted',
  },
  TASK_REVIEWED: {
    code: 'TASK_REVIEWED',
    module: 'task',
    category: 'task',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Task Reviewed',
    messageTemplate: 'Your task submission has been reviewed.',
    actionUrl: '/my-tasks',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'task:reviewed',
  },
  TASK_REASSIGNED: {
    code: 'TASK_REASSIGNED',
    module: 'task',
    category: 'task',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Task Reassigned',
    messageTemplate: 'A task has been reassigned to you. Please review.',
    actionUrl: '/my-tasks',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'task:reassigned',
  },
  TASK_DEADLINE_CHANGED: {
    code: 'TASK_DEADLINE_CHANGED',
    module: 'task',
    category: 'task',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Task Deadline Changed',
    messageTemplate: 'A task deadline has been updated. Please check the new deadline.',
    actionUrl: '/my-tasks',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'task:deadline_changed',
  },
  TASK_CANCELLED: {
    code: 'TASK_CANCELLED',
    module: 'task',
    category: 'task',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Task Cancelled',
    messageTemplate: 'A task has been cancelled.',
    actionUrl: '/my-tasks',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'task:cancelled',
  },
  TASK_DEADLINE_REMINDER: {
    code: 'TASK_DEADLINE_REMINDER',
    module: 'task',
    category: 'task',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Task Deadline Reminder',
    messageTemplate: 'You have a task with an approaching deadline.',
    actionUrl: '/my-tasks',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'task:deadline_reminder',
  },

  TICKET_CREATED: {
    code: 'TICKET_CREATED',
    module: 'ticket',
    category: 'ticket',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'New Ticket',
    messageTemplate: 'A new ticket has been created and requires assignment.',
    actionUrl: '/ticket-management',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'ticket:created',
  },
  TICKET_ASSIGNED: {
    code: 'TICKET_ASSIGNED',
    module: 'ticket',
    category: 'ticket',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Ticket Assigned',
    messageTemplate: 'A ticket has been assigned to you.',
    actionUrl: '/my-tickets',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'ticket:assigned',
  },
  TICKET_ESCALATED: {
    code: 'TICKET_ESCALATED',
    module: 'ticket',
    category: 'ticket',
    priority: 'high',
    channels: ['in_app', 'push'],
    titleTemplate: 'Ticket Escalated',
    messageTemplate: 'A ticket has been escalated. Please review.',
    actionUrl: '/ticket-management',
    quietHoursExempt: true,
    sensitive: false,
    idempotencyPrefix: 'ticket:escalated',
  },
  TICKET_RESOLVED: {
    code: 'TICKET_RESOLVED',
    module: 'ticket',
    category: 'ticket',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Ticket Resolved',
    messageTemplate: 'Your ticket has been resolved.',
    actionUrl: '/my-tickets',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'ticket:resolved',
  },
  TICKET_CLOSED: {
    code: 'TICKET_CLOSED',
    module: 'ticket',
    category: 'ticket',
    priority: 'normal',
    channels: ['in_app'],
    titleTemplate: 'Ticket Closed',
    messageTemplate: 'Your ticket has been closed.',
    actionUrl: '/my-tickets',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'ticket:closed',
  },
  TICKET_REOPENED: {
    code: 'TICKET_REOPENED',
    module: 'ticket',
    category: 'ticket',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Ticket Reopened',
    messageTemplate: 'A ticket has been reopened.',
    actionUrl: '/ticket-management',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'ticket:reopened',
  },
  TICKET_SLA_WARNING: {
    code: 'TICKET_SLA_WARNING',
    module: 'ticket',
    category: 'ticket',
    priority: 'high',
    channels: ['in_app', 'push'],
    titleTemplate: 'SLA Approaching',
    messageTemplate: 'A ticket SLA deadline is approaching.',
    actionUrl: '/ticket-management',
    quietHoursExempt: true,
    sensitive: false,
    idempotencyPrefix: 'ticket:sla_warning',
  },
  TICKET_SLA_BREACHED: {
    code: 'TICKET_SLA_BREACHED',
    module: 'ticket',
    category: 'ticket',
    priority: 'urgent',
    channels: ['in_app', 'push'],
    titleTemplate: 'SLA Breached',
    messageTemplate: 'A ticket SLA has been breached. Immediate action required.',
    actionUrl: '/ticket-management',
    quietHoursExempt: true,
    sensitive: false,
    idempotencyPrefix: 'ticket:sla_breached',
  },

  DAILY_REPORT_DUE: {
    code: 'DAILY_REPORT_DUE',
    module: 'daily_report',
    category: 'daily_report',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Daily Report Due',
    messageTemplate: 'Your daily report is due soon. Please submit before the cutoff time.',
    actionUrl: '/daily-report',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'report:due',
  },
  DAILY_REPORT_MISSING: {
    code: 'DAILY_REPORT_MISSING',
    module: 'daily_report',
    category: 'daily_report',
    priority: 'high',
    channels: ['in_app', 'push'],
    titleTemplate: 'Daily Report Missing',
    messageTemplate: 'Your daily report was not submitted. Please contact your manager.',
    actionUrl: '/daily-report',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'report:missing',
  },
  DAILY_REPORT_REVIEWED: {
    code: 'DAILY_REPORT_REVIEWED',
    module: 'daily_report',
    category: 'daily_report',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Daily Report Reviewed',
    messageTemplate: 'Your daily report has been reviewed.',
    actionUrl: '/my-report-history',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'report:reviewed',
  },
  DAILY_REPORT_RETURNED: {
    code: 'DAILY_REPORT_RETURNED',
    module: 'daily_report',
    category: 'daily_report',
    priority: 'high',
    channels: ['in_app', 'push'],
    titleTemplate: 'Daily Report Returned',
    messageTemplate: 'Your daily report has been returned for revision. Please review and resubmit.',
    actionUrl: '/daily-report',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'report:returned',
  },
  DAILY_REPORT_REOPENED: {
    code: 'DAILY_REPORT_REOPENED',
    module: 'daily_report',
    category: 'daily_report',
    priority: 'high',
    channels: ['in_app', 'push'],
    titleTemplate: 'Daily Report Reopened',
    messageTemplate: 'Your daily report has been reopened for editing.',
    actionUrl: '/daily-report',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'report:reopened',
  },
  FOLLOW_UP_ASSIGNED: {
    code: 'FOLLOW_UP_ASSIGNED',
    module: 'daily_report',
    category: 'follow_up',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Follow-up Assigned',
    messageTemplate: 'A follow-up has been assigned to you.',
    actionUrl: '/follow-up-queue',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'followup:assigned',
  },
  FOLLOW_UP_DUE: {
    code: 'FOLLOW_UP_DUE',
    module: 'daily_report',
    category: 'follow_up',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Follow-up Due',
    messageTemplate: 'You have a follow-up that is due soon.',
    actionUrl: '/follow-up-queue',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'followup:due',
  },
  FOLLOW_UP_OVERDUE: {
    code: 'FOLLOW_UP_OVERDUE',
    module: 'daily_report',
    category: 'follow_up',
    priority: 'high',
    channels: ['in_app', 'push'],
    titleTemplate: 'Follow-up Overdue',
    messageTemplate: 'You have an overdue follow-up that requires attention.',
    actionUrl: '/follow-up-queue',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'followup:overdue',
  },

  EMPLOYEE_INVITATION_SENT: {
    code: 'EMPLOYEE_INVITATION_SENT',
    module: 'employee',
    category: 'employee',
    priority: 'normal',
    channels: ['email'],
    titleTemplate: 'Welcome to Navjyoti HRMS',
    messageTemplate: 'You have been invited to join the organization. Please set up your password to activate your account.',
    actionUrl: '/set-password',
    quietHoursExempt: true,
    sensitive: false,
    idempotencyPrefix: 'emp:invitation_sent',
  },
  EMPLOYEE_ACTIVATED: {
    code: 'EMPLOYEE_ACTIVATED',
    module: 'employee',
    category: 'employee',
    priority: 'normal',
    channels: ['in_app'],
    titleTemplate: 'Account Activated',
    messageTemplate: 'Your account has been activated. You can now access the HRMS.',
    actionUrl: '/',
    quietHoursExempt: true,
    sensitive: false,
    idempotencyPrefix: 'emp:activated',
  },
  EMPLOYEE_ROLE_CHANGED: {
    code: 'EMPLOYEE_ROLE_CHANGED',
    module: 'employee',
    category: 'employee',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Role Changed',
    messageTemplate: 'Your role has been updated. You may have new permissions.',
    actionUrl: '/',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'emp:role_changed',
  },
  EMPLOYEE_MANAGER_CHANGED: {
    code: 'EMPLOYEE_MANAGER_CHANGED',
    module: 'employee',
    category: 'employee',
    priority: 'normal',
    channels: ['in_app'],
    titleTemplate: 'Reporting Manager Changed',
    messageTemplate: 'Your reporting manager has been updated.',
    actionUrl: '/',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'emp:manager_changed',
  },
  EMPLOYEE_DEPARTMENT_CHANGED: {
    code: 'EMPLOYEE_DEPARTMENT_CHANGED',
    module: 'employee',
    category: 'employee',
    priority: 'normal',
    channels: ['in_app'],
    titleTemplate: 'Department Changed',
    messageTemplate: 'Your department assignment has been updated.',
    actionUrl: '/',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'emp:dept_changed',
  },
  EMPLOYEE_BRANCH_CHANGED: {
    code: 'EMPLOYEE_BRANCH_CHANGED',
    module: 'employee',
    category: 'employee',
    priority: 'normal',
    channels: ['in_app'],
    titleTemplate: 'Branch Changed',
    messageTemplate: 'Your branch assignment has been updated.',
    actionUrl: '/',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'emp:branch_changed',
  },
  EMPLOYEE_SUSPENDED: {
    code: 'EMPLOYEE_SUSPENDED',
    module: 'employee',
    category: 'employee',
    priority: 'high',
    channels: ['in_app', 'push'],
    titleTemplate: 'Account Suspended',
    messageTemplate: 'Your account has been suspended. Please contact HR.',
    actionUrl: '/',
    quietHoursExempt: true,
    sensitive: false,
    idempotencyPrefix: 'emp:suspended',
  },
  EMPLOYEE_REACTIVATED: {
    code: 'EMPLOYEE_REACTIVATED',
    module: 'employee',
    category: 'employee',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Account Reactivated',
    messageTemplate: 'Your account has been reactivated. You can now access the HRMS.',
    actionUrl: '/',
    quietHoursExempt: true,
    sensitive: false,
    idempotencyPrefix: 'emp:reactivated',
  },
  EMPLOYEE_OFFBOARDED: {
    code: 'EMPLOYEE_OFFBOARDED',
    module: 'employee',
    category: 'employee',
    priority: 'high',
    channels: ['in_app'],
    titleTemplate: 'Account Offboarded',
    messageTemplate: 'Your account has been offboarded. Access is now restricted.',
    actionUrl: '/',
    quietHoursExempt: true,
    sensitive: false,
    idempotencyPrefix: 'emp:offboarded',
  },

  CALENDAR_HOLIDAY_CREATED: {
    code: 'CALENDAR_HOLIDAY_CREATED',
    module: 'calendar',
    category: 'calendar',
    priority: 'low',
    channels: ['in_app'],
    titleTemplate: 'New Holiday',
    messageTemplate: 'A new holiday has been added to the calendar.',
    actionUrl: '/calendar',
    quietHoursExempt: true,
    sensitive: false,
    idempotencyPrefix: 'cal:holiday_created',
  },
  CALENDAR_EVENT_CREATED: {
    code: 'CALENDAR_EVENT_CREATED',
    module: 'calendar',
    category: 'calendar',
    priority: 'normal',
    channels: ['in_app'],
    titleTemplate: 'New Calendar Event',
    messageTemplate: 'A new event has been added to the calendar.',
    actionUrl: '/calendar',
    quietHoursExempt: true,
    sensitive: false,
    idempotencyPrefix: 'cal:event_created',
  },
  CALENDAR_EVENT_REMINDER: {
    code: 'CALENDAR_EVENT_REMINDER',
    module: 'calendar',
    category: 'calendar',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Event Reminder',
    messageTemplate: 'You have an upcoming calendar event.',
    actionUrl: '/calendar',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'cal:event_reminder',
  },

  ANNOUNCEMENT_CREATED: {
    code: 'ANNOUNCEMENT_CREATED',
    module: 'announcement',
    category: 'announcement',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'New Announcement',
    messageTemplate: 'A new announcement has been posted. Please review it.',
    actionUrl: '/announcements',
    quietHoursExempt: false,
    sensitive: false,
    idempotencyPrefix: 'ann:created',
  },
  ANNOUNCEMENT_URGENT: {
    code: 'ANNOUNCEMENT_URGENT',
    module: 'announcement',
    category: 'announcement',
    priority: 'urgent',
    channels: ['in_app', 'push'],
    titleTemplate: 'Urgent Announcement',
    messageTemplate: 'An urgent organization announcement has been posted. Please review immediately.',
    actionUrl: '/announcements',
    quietHoursExempt: true,
    sensitive: false,
    idempotencyPrefix: 'ann:urgent',
  },

  EXPORT_COMPLETED: {
    code: 'EXPORT_COMPLETED',
    module: 'system',
    category: 'system',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'Export Completed',
    messageTemplate: 'Your export is ready for download.',
    actionUrl: '/export-center',
    quietHoursExempt: true,
    sensitive: false,
    idempotencyPrefix: 'export:completed',
  },
  EXPORT_FAILED: {
    code: 'EXPORT_FAILED',
    module: 'system',
    category: 'system',
    priority: 'high',
    channels: ['in_app', 'push'],
    titleTemplate: 'Export Failed',
    messageTemplate: 'Your export request failed. Please try again or contact support.',
    actionUrl: '/export-center',
    quietHoursExempt: true,
    sensitive: false,
    idempotencyPrefix: 'export:failed',
  },

  SECURITY_PASSWORD_CHANGED: {
    code: 'SECURITY_PASSWORD_CHANGED',
    module: 'security',
    category: 'security',
    priority: 'high',
    channels: ['in_app', 'push'],
    titleTemplate: 'Password Changed',
    messageTemplate: 'Your password has been changed. If this was not you, please contact support immediately.',
    actionUrl: '/account-settings',
    quietHoursExempt: true,
    sensitive: false,
    idempotencyPrefix: 'sec:password_changed',
  },
  SECURITY_NEW_DEVICE: {
    code: 'SECURITY_NEW_DEVICE',
    module: 'security',
    category: 'security',
    priority: 'normal',
    channels: ['in_app', 'push'],
    titleTemplate: 'New Device Registered',
    messageTemplate: 'A new device has registered for push notifications on your account.',
    actionUrl: '/account-settings',
    quietHoursExempt: true,
    sensitive: false,
    idempotencyPrefix: 'sec:new_device',
  },
  SECURITY_PUSH_REMOVED: {
    code: 'SECURITY_PUSH_REMOVED',
    module: 'security',
    category: 'security',
    priority: 'normal',
    channels: ['in_app'],
    titleTemplate: 'Push Device Removed',
    messageTemplate: 'A push notification device has been removed from your account.',
    actionUrl: '/account-settings',
    quietHoursExempt: true,
    sensitive: false,
    idempotencyPrefix: 'sec:push_removed',
  },
}

export function getEventDef(code: string): NotificationEventDef | undefined {
  return NOTIFICATION_EVENTS[code]
}

export function shouldPushForEvent(def: NotificationEventDef): boolean {
  return def.channels.includes('push')
}

export function shouldEmailForEvent(def: NotificationEventDef): boolean {
  return def.channels.includes('email')
}

export function shouldInAppForEvent(def: NotificationEventDef): boolean {
  return def.channels.includes('in_app')
}
